config/routes.rb
Rails.application.routes.draw do
  resources :lists, :constraints => {:format => /(html)/}

  root 'home#index'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/item.rb
class Item < ActiveRecord::Base
  acts_as_taggable
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :items, :dependent => :destroy
  accepts_nested_attributes_for :items, :allow_destroy => true


  def is_owned_by(current_user)
    if current_user.id === self.user_id
      return true
    else
      return false
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :lists


  def self.from_omniauth(auth)
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end
  
  def self.create_from_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.nickname = auth["info"]["nickname"]
      user.name = auth["info"]["name"]
      user.image = auth["info"]["image"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authenticate
    if current_user
    else
      flash[:alert] = "You must log in before accessing this page."
      redirect_to :root unless current_user
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate

  # GET /lists
  # GET /lists.json
  def index
    @lists = current_user.lists
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    check_permission
    if params[:tag].present? 
      @items = @list.items.tagged_with(params[:tag])
      @random_choice = @items.sample
    else 
      @items = @list.items.all
      @random_choice = @items.sample
    end
    @tags = @list.items.tag_counts_on(:tags)
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
    check_permission
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    @list.user_id = current_user.id
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    check_permission
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:name, items_attributes: [:id, :list_id, :name, :_destroy, :tag_list] )
    end

    def check_permission
      if @list.is_owned_by(current_user)
      else
        redirect_to root_url, alert: 'You don\'t own that list.'
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
  include ActsAsTaggableOn::TagsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_footer.html.haml
.container
  .row
    .col-md-12
      %hr
      %footer
  .row
    .col-md-6
      %p
        %a{:href => 'https://creativecommons.org/licenses/by/4.0/'}
        = image_tag "cc.png"
        = Time.now.year
        %a{:href => 'http://samurailink3.com'}
          Tom "SamuraiLink3" Webster
    .col-md-6
      %p.pull-right
        Code licensed under the
        %a{:href => 'http://opensource.org/licenses/MIT'} MIT License
        and available at
        %a{:href => 'https://github.com/samurailink3/tagged_app/'} GitHub
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-2406517-11', 'samurailink3.com');
  ga('send', 'pageview');
/ Piwik
:javascript
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u=(("https:" == document.location.protocol) ? "https" : "http") + "://stats.samurailink3.com/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 7]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript';
    g.defer=true; g.async=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
%noscript
  %p
    %img{:alt => "", :src => "http://stats.samurailink3.com/piwik.php?idsite=7", :style => "border:0;"}/
/ End Piwik Code

app/views/application/_header.html.haml
.navbar.navbar-default
  .navbar-header
    %button.navbar-toggle{"data-toggle" => "collapse", "data-target" => "#navbar-collapse-1"}
      %span.sr-only Toggle Navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a= link_to "Tagged", root_path, :class => "navbar-brand"
  #navbar-collapse-1.collapse.navbar-collapse
    %ul.nav.navbar-nav
      %li
        %a{:href => "http://samurailink3.com"} Who made this?
      %li
        %a{:href => "https://github.com/samurailink3/tagged_app"} Can I get one?
      %li
        %a{:href => "http://opensource.org/licenses/MIT"} Is it free?
      %li
        %a{:href => "https://creativecommons.org/licenses/by/4.0/"} Are you sure?
    %ul.nav.navbar-nav.navbar-right
      - if current_user
        %li
          = link_to "<span class='glyphicon glyphicon-list'></span> My Lists".html_safe, lists_path
        %li
          .navbar-form
            .btn-group
              %button.btn.btn-primary.dropdown-toggle{:data => {:toggle => 'dropdown'}}
                %img{:src => current_user.image, :height => '24px'}
                = current_user.nickname
                %span.caret
              %ul.dropdown-menu{:role => 'menu'}
                %li
                  %a{:href => '/signout'}
                    %span.glyphicon.glyphicon-off
                    Sign Out
      - else
        %li
          .navbar-form
            %a.btn.btn-primary{:href => "/auth/twitter", :style => "color: white;"}
              %span.glyphicon.glyphicon-user
              Sign in with Twitter

app/views/home/index.html.haml
.jumbotron
  .container
    .row
      .col-md-6
        %h1
          Tagged!
          %small Tag! Your! Lists!
        %h2
          %small Tagged allows you to create lists, put items in those lists, tag those items, filter on those tags, then randomly select an item from that much smaller list. Why is this helpful? Read on:
      .col-md-6
        .pull-right= image_tag "front.png"
.container
  .row
    .col-md-6
      .pull-right{ :style => 'margin-right: 1%; margin-bottom: 1%;'}= image_tag "list.png"
    .col-md-6
      %h2
        %span.glyphicon.glyphicon-list-alt
        Lists!
      %h4 Tagged allows you to create as many lists and you damn well please. Create a list with one thing, or one-hundred. I don't care, neither should you. Create todo lists, grocery lists, fast food lists, multiplayer shooter lists, whatever.
  .row
    .col-md-6
      .pull-right{ :style => 'margin-right: 1%; margin-bottom: 1%;'}= image_tag "item.png"
    .col-md-6
      %h2
        %span.glyphicon.glyphicon-list
        Items!
      %h4
        This could be a foreign concept to some people... but... Lists contain
        %strong items.
        Tagged allows you to tag (GASP) items in a list. Why? Keep scrollin', cowboy.
  .row
    .col-md-6
      .pull-right{ :style => 'margin-right: 1%; margin-bottom: 1%;'}= image_tag "tag.png"
    .col-md-6
      %h2
        %span.glyphicon.glyphicon-tags
        Tags!
      %h4 Tags are the most important part of Tagged. You can put as many tags as you want on an item, click the tag, and see other objects that have that tag. Plain english version: Let's say I'm deciding where to eat, I don't want fast food, so I click the "sit down" tag. I really want a place with a good burger, so I'll click "burger", and while I'm at it, let's go to a place with a decent beer selection. *Clicks "great beer selection". There, now I have 3 places to choose from. Which one, though? I'll click the "Choose for Me!" button and I'll be on my way.

  .row
    .col-md-12
      %h1
        %strong The Official Often Asked Questions Area &copy;
      #accordion.panel-group
        .panel.panel-default
          .panel-heading
            %h2.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseOne"}
                What does this this do?
          #collapseOne.panel-collapse.collapse.in
            .panel-body
              %h5
                Plain and simple: Make a list of stuff, filter it by tags, the app chooses one at random, that's your choice. It helps you make semi-informed decisions.
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseTwo"}
                Why the hell would you waste your time on this?
          #collapseTwo.panel-collapse.collapse
            .panel-body
              %h5
                I'm in the middle of a big Rails kick, so I decided to take on a personal challenge: Actually finish a project (even a small one). I had a problem: My girlfriend and I can't ever decide where to eat. My solution: Build a filterable list that will make the decision for us.
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseThree"}
                Seriously?
          #collapseThree.panel-collapse.collapse
            .panel-body
              = image_tag "serious.gif"
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseFour"}
                Can I use this for x/y/z?
          #collapseFour.panel-collapse.collapse
            .panel-body
              %h5
                I honestly don't care, go for it. Want to use it for a raffle? A contest? To decide the outcome of a gladiator battle? Go for it, but understand, you cannot hold me liable. This software has no guarantees or warranties of any kind. Read the
                = link_to "license here.", "http://opensource.org/licenses/MIT"
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseFive"}
                Who the hell made this?
          #collapseFive.panel-collapse.collapse
            .panel-body
              %h5
                = link_to "I did.", "http://samurailink3.com"
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseSix"}
                Can I have the source code? Can I make this better? Are you accepting pull requests? Your design looks like shit.
          #collapseSix.panel-collapse.collapse
            .panel-body
              %h5
                1.
                = link_to "Yes you can.", "https://github.com/samurailink3/tagged_app"
              %h5
                2 & 3. Yep!
                = link_to "Pull requests go here.", "https://github.com/samurailink3/tagged_app"
              %h5
                4. That's not a question.
                =link_to "Send a pull request.", "https://github.com/samurailink3/tagged_app"
        .panel.panel-default
          .panel-heading
            %h4.panel-title
              %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#collapseSeven"}
                Can I hire you to "code my webapp"/"make a website"/"walk my dog"/"build me a shed"/"be my bodyguard"?
          #collapseSeven.panel-collapse.collapse
            .panel-body
              %h5
                I'm always looking for interesting projects. Check out
                = link_to "my credentials here", "http://samurailink3.com/hireme/cv/"
                and if you're interested
                = link_to "shoot me an email here.", "mailto:samurailink3@gmail.com"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      Tagged
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render :partial => "header"
    - if flash[:notice]
      .container
        .row
          .col-md-8.col-md-offset-2
            .alert.alert-info.alert-dismissable
              %button.close{:type => 'button', :aria => { :hidden => 'true' }, :data => { :dismiss => 'alert' } } &times;
              = flash[:notice]
    - if flash[:alert]
      .container
        .row
          .col-md-8.col-md-offset-2
            .alert.alert-danger.alert-dismissable
              %button.close{:type => 'button', :aria => { :hidden => 'true' }, :data => { :dismiss => 'alert' } } &times;
              = flash[:alert]
    = yield
    = render :partial => "footer"

app/views/lists/_form.html.haml
= nested_form_for @list do |f|
  .row
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title List Instructions:
        .panel-body
          %p
            Here you can name your
            %strong list
            , call it anything you'd like.
    .col-md-6
      .panel.panel-info
        .panel-heading
          %h3.panel-title Item Instructions:
        .panel-body
          %p
            Create items here, use the
            %strong '+' and '-' buttons
            to add and remove list items. You can also tag certain items by using a
            %strong comma-separated
            list.
  .row
    .col-md-6
      - if @list.errors.any?
        #error_explanation
          %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
          %ul
            - @list.errors.full_messages.each do |msg|
              %li= msg
      .form-group.form-inline
        = f.label :name, "List Name"
        = f.text_field :name, :class => 'form-control'
    .col-md-6
      = f.fields_for :items
      = f.link_to_add "<div class='btn btn-md btn-success'><span class='glyphicon glyphicon-plus' style='color: white;'></span></div>".html_safe, :items
  .row
    .col-md-2
      .actions
        %button.btn.btn-lg.btn-success{:type => 'submit'}
          %span.glyphicon.glyphicon-save
          Save

app/views/lists/_item_fields.haml
.form-group.form-inline
  = f.label :name, "Item Name"
  = f.text_field :name, :class => 'form-control'
  = f.label :tags
  = f.text_field :tag_list
  = f.link_to_remove "<div class='btn btn-md btn-danger'><span class='glyphicon glyphicon-minus' style='color: white;'></span></div>".html_safe

app/views/lists/edit.html.haml
.container
  .row
    .col-md-12
      %h1 Editing List
  = render 'form'
  .row
    .col-md-2.col-md-offset-10
      = link_to '<span class="glyphicon glyphicon-eye-open"></span> Show'.html_safe, @list, :class => '.btn btn-sm btn-primary', :style => 'color: white;'
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, lists_path, :class => '.btn btn-sm btn-primary', :style => 'color: white;'

app/views/lists/index.html.haml
.container
  .row
    .col-md-12
      %h1 My Lists
  .row
    .col-md-12
      %table.table.table-responsive.table-striped
        %tr
          %th Name
          %th Number of Items
          %th
        - @lists.each do |list|
          %tr
            %td= link_to list.name, list
            %td= list.items.count
            %td
              = link_to '<span class="glyphicon glyphicon-eye-open"></span>'.html_safe, list_path(list), :class => '.btn btn-sm btn-primary', :style => 'color: white;'
              = link_to '<span class="glyphicon glyphicon-pencil"></span>'.html_safe, edit_list_path(list), :class => '.btn btn-sm btn-warning', :style => 'color: white;'
              = link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, list, :class => '.btn btn-sm btn-danger', :style => 'color: white;', :method => :delete, :data => { :confirm => 'Are you sure?' }
  .row
    .col-md-12
      = link_to '<span class="glyphicon glyphicon-plus"></span>'.html_safe, new_list_path, :class => 'btn btn-lg btn-success pull-right', :style => 'color: white;'

app/views/lists/new.html.haml
.container
  .row
    .col-md-12
      %h1 New List
      = render 'form'
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, lists_path, :class => '.btn btn-sm btn-primary', :style => 'color: white;'

app/views/lists/show.html.haml
- if @items.count > 0
  .modal.fade.bs-example-modal-lg{:role => "dialog", :tabindex => "-1", :aria => { :hidden => "true", :labelledby => "myLargeModalLabel" } }
    .modal-dialog.modal-lg
      .modal-content
        .modal-header
          %h4 Your randomly selected choice is:
        .modal-body
          %h1= @random_choice.name
        .modal-footer
          = link_to "<span class='glyphicon glyphicon-remove-circle'></span> I don't like it...".html_safe, request.original_url, :class => 'btn btn-warning', :style => 'color: white;'
          %button.btn.btn-success{"data-dismiss" => "modal", :type => "button"}
            %span.glyphicon.glyphicon-ok-circle
            Looks good!
- else
  .modal.fade.bs-example-modal-lg{:role => "dialog", :tabindex => "-1", :aria => { :hidden => "true", :labelledby => "myLargeModalLabel" } }
    .modal-dialog.modal-lg
      .modal-content
        .modal-header
          %h4 Your randomly selected choice is:
        .modal-body
          %h1 Absolutely Nothing!
          %h2 You lose!
          %h3 Good day, sir!
          %br
          %p You didn't have anything to pick from :(
        .modal-footer
          = link_to "<span class='glyphicon glyphicon-remove-circle'></span> I don't like it...".html_safe, request.original_url, :class => 'btn btn-warning', :style => 'color: white;'
          %button.btn.btn-success{"data-dismiss" => "modal", :type => "button"}
            %span.glyphicon.glyphicon-ok-circle
            Looks good!
.container
  .row
    .col-md-2
      %h4
        Use tags to filter
        %span.glyphicon.glyphicon-arrow-right
    .col-md-8
      - tag_cloud(@tags, ['btn btn-primary btn-xs', 'btn btn-primary btn-sm', 'btn btn-primary btn', 'btn btn-primary btn-lg']) do |tag, css_class|
        - if(params.has_key?(:tag))
          = link_to "<span class='glyphicon glyphicon-tag'></span> ".html_safe + tag.name, request.original_url + "," + tag.name, { :style => 'color: white; text-decoration: none;', :class => css_class}
        - else
          = link_to "<span class='glyphicon glyphicon-tag'></span> ".html_safe + tag.name, request.original_url + "?tag=" + tag.name, { :style => 'color: white; text-decoration: none;', :class => css_class}
    .col-md-2
      = link_to "<span class='glyphicon glyphicon-refresh'></span> Reset Tags".html_safe, list_path(@list), :class => 'btn btn-warning', :style => 'color: white;'
    %br
    %br
  .row
    .col-md-6
      %p#notice= notice
      %h3
        %b List:
        = @list.name
      %p{:style => 'text-align: center;'}
        %span.glyphicon.glyphicon-arrow-down
        Use tags to narrow your choices, the hit the giant button below
        %span.glyphicon.glyphicon-arrow-down
      %button.btn.btn-lg.btn-success.form-control{:data => { :target => ".bs-example-modal-lg", :toggle => "modal" } }
        %span.glyphicon.glyphicon-gift
        Choose one for Me!
        %span.glyphicon.glyphicon-gift
    .col-md-6
      %table.table.table-responsive.table-striped
        %tr
          %th Item
          %th Tags
          - @items.each do |item|
            %tr
              %td= item.name
              %td
                - item.tags.each do |tag|
                  - if(params.has_key?(:tag))
                    %span.h1.label.label-primary= link_to tag.name, request.original_url + "," + tag.name, { :style => 'color: white; text-decoration: none;' }
                  - else
                    %span.h1.label.label-primary= link_to tag.name, request.original_url + "?tag=" + tag.name, { :style => 'color: white; text-decoration: none;' }
  .row
    .col-md-2.col-md-offset-10
      = link_to '<span class="glyphicon glyphicon-pencil"></span> Edit'.html_safe, edit_list_path(@list), :class => '.btn btn-sm btn-warning', :style => 'color: white;'
      = link_to '<span class="glyphicon glyphicon-arrow-left"></span> Back'.html_safe, lists_path, :class => '.btn btn-sm btn-primary', :style => 'color: white;'